<?php
    $title = "Bungalov 60 2+kk";
	$active = "typove-domy";
	include("../includes/hlavicka.php");
?>
            <div class="row-fluid">
                <div class="span8 well">
	<h2>Bungalov 60 2+kk</h2>
<div><strong style="font-family: tahoma, arial, helvetica, sans-serif; line-height: 150%;"><span style="font-size: 10pt; line-height: 150%;"><img style="float: left; margin-right: 20px;" alt="Bungalov 60" src="../images/typove_domy/Bungalov_60.jpg" width="184" height="114" />Počet podlaží:</span></strong><span style="font-family: tahoma, arial, helvetica, sans-serif; line-height: 150%;" class="apple-converted-space"><span style="font-size: 10pt; line-height: 150%;">&nbsp;</span></span><span style="font-size: 10pt; line-height: 150%;">1</span></div>
<div><strong style="font-family: tahoma, arial, helvetica, sans-serif; line-height: 150%;">Dispozice:</strong><span style="font-family: tahoma, arial, helvetica, sans-serif; line-height: 150%;" class="apple-converted-space">&nbsp;</span><span style="font-family: tahoma, arial, helvetica, sans-serif; line-height: 150%;">2+kk</span></div>
<div><strong style="font-family: tahoma, arial, helvetica, sans-serif; line-height: 150%;"><span style="font-size: 10pt; line-height: 150%;">Zastavěná plocha:</span></strong><span style="font-family: tahoma, arial, helvetica, sans-serif; line-height: 150%;" class="apple-converted-space"><span style="font-size: 10pt; line-height: 150%;">&nbsp;</span></span><span style="font-size: 10pt; line-height: 150%;">60,3m2</span></div>
<div><strong style="font-family: tahoma, arial, helvetica, sans-serif; line-height: 150%;"><span style="font-size: 10pt; line-height: 150%;">Stavba na klíč:</span></strong><span style="font-family: tahoma, arial, helvetica, sans-serif; line-height: 150%;" class="apple-converted-space"><span style="font-size: 10pt; line-height: 150%;">&nbsp;</span></span><span style="font-size: 10pt; line-height: 150%;">od 1.089.000,- bez DPH</span></div>
<div><strong style="font-family: tahoma, arial, helvetica, sans-serif; line-height: 150%;"><span style="font-size: 10pt; line-height: 150%;">Hrubá stavba:</span></strong><span style="font-family: tahoma, arial, helvetica, sans-serif; line-height: 150%;" class="apple-converted-space"><span style="font-size: 10pt; line-height: 150%;">&nbsp;</span></span><span style="font-size: 10pt; line-height: 150%;">od 649.000,- bez DPH</span></div>
<div><span style="font-size: 10pt; line-height: 150%; font-family: tahoma, arial, helvetica, sans-serif;">Ceny uvedené pro základní vybavenost</span></div>
<p style="margin-bottom: 0cm;" class="western"><span style="color: #ff0000;" color="#ff0000"><span style="font-size: 0px; line-height: 0px;">&nbsp;</span></span></p>
<p>&nbsp;<span style="font-family: Tahoma, sans-serif; font-size: 10pt; line-height: 150%;">Dům je menší rozměrové kategorie a je vhodný pro dvou člennou začínající rodinu, starší lidi, dům pro hosty a rekreační objekt. Projekt možno zrcadly popřípadě jakkoliv upravit.</span></p>
<p style="margin-bottom: 0.0001pt; line-height: 150%;"><b><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">&nbsp;</span></b><img style="margin: 20px;" alt="Bungalov 60P" src="../images/typove_domy_pudorysy/Bungalov_60P.jpg" width="280" height="250" /></p>
<p style="margin-bottom: 0.0001pt; line-height: 150%;"><b><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Základní vybavenost:</span></b><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;"></span></p>
<p style="margin-bottom: 0.0001pt; line-height: 150%;"><b><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Soupis dodaných prací včetně materiálů obsažených v&nbsp;ceně díla v&nbsp;základní vybavenosti</span></b><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;"></span></p>
<p style="margin-bottom: 0.0001pt; line-height: 150%;"><b><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Varianta YTONG – HELUZ + dodatečné zateplení</span></b><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;"></span></p>
<p style="margin-bottom: 0.0001pt; line-height: 150%; text-align: right;" align="center"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">&nbsp;</span></p>
<p style="margin-bottom: 0.0001pt; line-height: 150%;"><b><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Příprava staveniště:</span></b><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;"></span></p>
<p style="margin-bottom: 0.0001pt; line-height: 150%;"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">&nbsp;- příprava staveniště nutná pro realizaci</span></p>
<p style="margin-bottom: 0.0001pt; line-height: 150%;"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">&nbsp;- zemní práce nutné před realizací stavby</span></p>
<p style="margin-bottom: 0.0001pt; line-height: 150%;"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">&nbsp;- vytyčení stavby dle PD</span></p>
<p style="margin-bottom: 0.0001pt; line-height: 150%;"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">&nbsp;- usazení na pozemek dle PD</span></p>
<p style="margin-bottom: 0.0001pt; line-height: 150%;"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">&nbsp;&nbsp;</span></p>
<p style="margin-bottom: 0.0001pt; line-height: 150%;"><b><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Základy a základová deska:</span></b><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;"></span></p>
<p style="margin-bottom: 0.0001pt; line-height: 150%;"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">&nbsp;- vyhloubení a vylití základových pásů včetně realizace potřebných průchodek dle PD</span></p>
<p style="margin-bottom: 0.0001pt; line-height: 150%;"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">&nbsp;- vyzdění a vybetonování ztraceného bednění nad úrovní základových pásů - výšky dle PD</span></p>
<p style="margin-bottom: 0.0001pt; line-height: 150%;"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">&nbsp;- vlastní betony základové desky včetně ležatých rozvodů kanalizace a vyústění průchodek</span></p>
<p style="margin-bottom: 0.0001pt; line-height: 150%;"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">&nbsp;- Hydro izolace lepenkou – max. STŘEDNÍ RADONOVÉ RIZIKO</span></p>
<p style="margin-bottom: 0.0001pt; line-height: 150%;"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">&nbsp;&nbsp;</span></p>
<p style="margin-bottom: 0.0001pt; line-height: 150%;"><b><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Svislé konstrukce:</span></b><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;"></span></p>
<p style="margin-bottom: 0.0001pt; line-height: 150%;"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">&nbsp;- Vyzdění veškerého nosného zdiva</span></p>
<p style="margin-bottom: 0.0001pt; line-height: 150%;"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">&nbsp;<i>Varianta HELUZ:</i></span></p>
<p style="margin-bottom: 0.0001pt; line-height: 150%;"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">&nbsp;HELUZ PLUS 30 tl.300mm NA CELOPLOŠNÉ LEPILO včetně systémových . překladů + dodatečné zateplení viz úprava vnějších zdí</span></p>
<p style="margin-bottom: 0.0001pt; line-height: 150%;"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">&nbsp;Vyzdění vnitřních příček: HELUZ 11,5 na lepidlo včetně nenosných překladů</span></p>
<p style="margin-bottom: 0.0001pt; line-height: 150%;"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">&nbsp;&nbsp;</span></p>
<p style="margin-bottom: 0.0001pt; line-height: 150%;"><b><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Varianta YTONG:</span></b><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;"></span></p>
<p style="margin-bottom: 0.0001pt; line-height: 150%;"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">&nbsp;YTONG P2-400 tl.300mm NA CELOPLOŠNÉ LEPILO včetně systémových . překladů + dodatečné zateplení viz úprava vnějších zdí</span></p>
<p style="margin-bottom: 0.0001pt; line-height: 150%;"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">&nbsp;Vyzdění vnitřních příček: YTONG tl.100 na lepidlo včetně nenosných překladů</span></p>
<p style="margin-bottom: 0.0001pt; line-height: 150%;"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">&nbsp;- Vyhotovení železobetonového obvodového věnce nad nosným zdivem, sloužící taktéž pro ukotvení krovů včetně tepelné izolace a věncovém dle PD</span></p>
<p style="margin-bottom: 0.0001pt; line-height: 150%;"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">&nbsp;</span></p>
<p style="margin-bottom: 0.0001pt; line-height: 150%;"><b><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Zastřešení stavby:</span></b><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;"></span></p>
<p style="margin-bottom: 0.0001pt; text-align: justify; line-height: 150%;"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">&nbsp;Krovy: klasické krovy popřípadě příhradové vazníky (volba zhotovitelem), ošetřené proti škůdcům bez přesahů za kontaktní vnější zateplení EPS-F.</span></p>
<p style="margin-bottom: 0.0001pt; text-align: justify; line-height: 150%;"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">&nbsp;Tašky: KM-BETA klasik včetně všech potřebných doplňků – ČERVENÁ, ČERNÁ A HNĚDÁ BARVA BARVA</span></p>
<p style="margin-bottom: 0.0001pt; text-align: justify; line-height: 150%;"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">&nbsp;Okapy, svody a oplechování: Pobarvený plech okapní svody budou zakončeny nad úrovní rostlého terénu</span></p>
<p style="margin-bottom: 0.0001pt; text-align: justify; line-height: 150%;"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">&nbsp;Hromosvod: dle elektro projektu</span></p>
<p style="margin-bottom: 0.0001pt; line-height: 150%;"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">&nbsp;&nbsp;</span></p>
<p style="margin-bottom: 0.0001pt; line-height: 150%;"><b><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Zdravotechnika:</span></b><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;"></span></p>
<p style="margin-bottom: 0.0001pt; line-height: 150%;"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">&nbsp;<b><span style="text-decoration: underline;">Voda:&nbsp;</span></b>rozvody podlahách a zdech přivedené na místo připojení zařizovacích předmětů dle PD a zaslepeny. Hlavní přívod vody k&nbsp;vodoměrné šachtě do 10m.</span></p>
<p style="margin-bottom: 0.0001pt; line-height: 150%;"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">&nbsp;Výroba teplé užitkové vody zabezpečí bojler 100 l.</span></p>
<p style="margin-bottom: 0.0001pt; line-height: 150%;"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">&nbsp;<b><span style="text-decoration: underline;">Kanalizace</span></b><span style="text-decoration: underline;">:</span>&nbsp;rozvody podlahách a zdech přivedené na místo připojení zařizovacích předmětů a zaslepeny. Hlavní přívod kanalizace k&nbsp;revizní kanalizační šachtě do 10m.</span></p>
<p style="margin-bottom: 0.0001pt; line-height: 150%;"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">&nbsp;<span style="text-decoration: underline;">Zařizovací předměty zdravotechniky:</span></span></p>
<p style="margin-bottom: 0.0001pt; line-height: 150%;"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">&nbsp;1 x standardní WC kombi v&nbsp;ceně včetně ovládacího zařízení do 2.400,- /kus včetně DPH</span></p>
<p style="margin-bottom: 0.0001pt; line-height: 150%;"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">&nbsp;1 x umyvadlo včetně baterie v&nbsp;ceně do 2.500,- /kus včetně DPH</span></p>
<p style="margin-bottom: 0.0001pt; line-height: 150%;"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">&nbsp;1 x sprchový kout stavebnice s&nbsp;vlastní baterií v&nbsp;celkové ceně do 8.000,- /kus včetně DPH</span></p>
<p style="margin-bottom: 0.0001pt; line-height: 150%;"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">&nbsp;&nbsp;</span></p>
<p style="margin-bottom: 0.0001pt; line-height: 150%;"><b><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Ústřední topení:</span></b><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;"></span></p>
<p style="margin-bottom: 0.0001pt; line-height: 150%;"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Zdrojem tepelné energie bude elektrokotel dle PD. Vlastní vytápění bude zabezpečeno celoplošným podlahovým vytápěním bez systémových desek – kotvení do podlahového polystyrénu na skoby. Mechanický pákový rozdělovač okruhů v&nbsp;systémové skříni.</span></p>
<p style="margin-bottom: 0.0001pt; line-height: 150%;"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">&nbsp;</span></p>
<p style="line-height: 150%;"><b><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Elektroinstalace:</span></b><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;"></span></p>
<p style="margin-bottom: 0.0001pt; line-height: 150%;"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Veškeré rozvody kabeláže ve zdech a podlahách pro zásuvky, osvětlení, varnou desku, taktéž pro 1 x vnější zásuvku na 220V a 380V. V&nbsp;místě zásuvek a vypínačů krabice s&nbsp;kabeláží připravené pro jejich instalaci. V&nbsp;místě světel kabeláž ze stropu připravená pro napojení daného osvětlení. V&nbsp;místě připojení varné desky krabice s&nbsp;kabeláží pro připojení. V&nbsp;místě Bojleru krabice s kabeláží pro připojení. Vnitřní domovní rozvaděč s&nbsp;potřebnými jističi dle PD. Přivedení silového kabelu k&nbsp;vnějšímu rozvaděči RM do 10m. Osazení vypínačů a zásuvek modelu KLASIK výrobce ABB standard bílé barvy. Vlastní osvětlovací zařízení (lustry, svítidla, bodovky atd.) nejsou součástí dodávky. Počty zásuvek a světel jsou počítány dle PD v&nbsp;nižším standardu.</span></p>
<p style="margin-bottom: 0.0001pt; line-height: 150%;"><b><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Součástí dodávky nejsou nízkonapěťové, televizní a datové rozvody.</span></b><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;"></span></p>
<p style="margin-bottom: 0.0001pt; line-height: 150%;"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">- kanalizační rozvody, rozvody TUV + SUV a elektro související s&nbsp;kuchyňskou linkou budou rozvedeny do předpokládaného místa připojení a zaslepeny.</span></p>
<p style="margin-bottom: 0.0001pt; line-height: 150%;"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">&nbsp;</span></p>
<p style="margin-bottom: 0.0001pt; line-height: 150%;"><b><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Výplně stavebních otvrů:</span></b><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;"></span></p>
<p style="margin-bottom: 0.0001pt; line-height: 150%;"><b><i><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Vnějších:</span></i></b><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;"></span></p>
<p style="margin: 0cm 0cm 0.0001pt 22.5pt; line-height: 150%;"><span style="text-decoration: underline;"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Okna, balkónové dveře:</span></span><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;"></span></p>
<p style="margin-bottom: 0.0001pt; line-height: 150%;"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Dodavatel:&nbsp;<b>VEKRA</b></span></p>
<p style="margin-bottom: 0.0001pt; line-height: 150%;"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Provedení: plastové 5-ti komorová profil&nbsp;<b>PRIMA</b></span></p>
<p style="margin-bottom: 0.0001pt; line-height: 150%;"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Barevnost: vnější a vnitřní barva bílá stejná barevnost vnějších plechových a vnitřních plastových parapetů</span></p>
<p style="margin-bottom: 0.0001pt; line-height: 150%;"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Zasklení: trojsklo bez okrasných vnitřních příček</span></p>
<p style="margin: 0cm 0cm 0.0001pt 22.5pt; line-height: 150%;"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">&nbsp;</span></p>
<p style="margin: 0cm 0cm 0.0001pt 22.5pt; line-height: 150%;"><span style="text-decoration: underline;"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Vchodové dveře:</span></span><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;"></span></p>
<p style="margin: 0cm 0cm 0.0001pt 22.5pt; line-height: 150%;"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Stejného systému jako okna s&nbsp;kováním vchodových dveří v&nbsp;patřičném profilu, výplň Izolační trojsklo popřípadě hladká deska</span></p>
<p style="margin: 0cm 0cm 0.0001pt 22.5pt; line-height: 150%;"><span style="text-decoration: underline;"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Střešní okna:</span></span><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">&nbsp;nejsou součástí dodávky</span></p>
<p style="margin-bottom: 0.0001pt; line-height: 150%;"><b><i><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Vnitřních:</span></i></b><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;"></span></p>
<p style="margin-bottom: 0.0001pt; line-height: 150%;"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">&nbsp;</span></p>
<p style="margin: 0cm 0cm 0.0001pt 22.5pt; line-height: 150%;"><span style="text-decoration: underline;"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Vnitřní dveře s&nbsp;obložkami:</span></span><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;"></span></p>
<p style="margin-bottom: 0.0001pt; line-height: 150%;"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">SAPELI STANDARD Model 10, 30, 40, 50, 60 a 65</span></p>
<p style="margin-bottom: 0.0001pt; line-height: 150%;"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Vybavení: Standardní bezpříplatkové</span></p>
<p style="margin-bottom: 0.0001pt; line-height: 150%;"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Sklo: dle výběru k&nbsp;danému tipu bezpříplatkové</span></p>
<p style="margin-bottom: 0.0001pt; line-height: 150%;"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Povrch dveří i obložek: fólie - bílá, dub, buk, třešeň, javor, hruška, bělený dub, olše, teak, wenge</span></p>
<p style="margin-bottom: 0.0001pt; line-height: 150%;"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Obložky: folie základního bezpříplatkového provedení potřebného tipu a materiálu ve vybrané barevnosti</span></p>
<p style="margin-bottom: 0.0001pt; line-height: 150%;"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Zámkový set a kliku: Z&nbsp;důvodu velkého výběru dodá investor sám, popřípadě bude řešena dodávka jako vícepráce</span></p>
<p style="margin-bottom: 0.0001pt; line-height: 150%;"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">&nbsp;</span></p>
<p style="margin-bottom: 0.0001pt; line-height: 150%;"><b><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Finální úpravy povrchů zdí, stropů a schodiště:</span></b><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;"></span></p>
<p style="margin-bottom: 0.0001pt; line-height: 150%;"><span style="text-decoration: underline;"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Vnější zdivo:</span></span><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;"></span></p>
<p style="margin-bottom: 0.0001pt; line-height: 150%;"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">- Pohledová boční strana základové desky obložená tepelnou izolací XPS tl.40mm ve viditelných částech natažená lepidlo + perlinka a okrasná zrnitá kamenitá fasáda</span></p>
<p style="margin-bottom: 0.0001pt; line-height: 150%;"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">- Vnější nosné zdivo: fasádní polystyrén EPS-F 70 tl.140mm + perlina + lepidlo + fasádní akrilátová omítka bílé barvy zrnitosti 1mm (točená)</span></p>
<p style="margin-bottom: 0.0001pt; line-height: 150%;"><span style="text-decoration: underline;"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Vnitřní zdivo:</span></span><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;"></span></p>
<p style="margin-bottom: 0.0001pt; line-height: 150%;"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">VC malta + štuk popřípadě perlina+lepidlo+štuk, bílá malba</span></p>
<p style="margin-bottom: 0.0001pt; line-height: 150%;"><span style="text-decoration: underline;"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Podhled stropů 1.NP:</span></span><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;"></span></p>
<p style="margin-bottom: 0.0001pt; line-height: 150%;"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Sádrokartón začištěný + s&nbsp;tepelnou izolací vatou URSA tl.360mm</span></p>
<p style="margin-bottom: 0.0001pt; line-height: 150%;"><span style="text-decoration: underline;"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Betonové mazaniny finálních podlah:</span></span><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;"></span></p>
<p style="margin-bottom: 0.0001pt; line-height: 150%;"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">- Podkladová tepelná izolace tl. 90 EPS-S dle PD a vlastní betony strojem hlazené</span></p>
<p style="margin-bottom: 0.0001pt; line-height: 150%;"><span style="text-decoration: underline;"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Vnitřní vymalování:</span></span><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;"></span></p>
<p style="margin-bottom: 0.0001pt; line-height: 150%;"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">- Bílou barvou PRIMALEX</span></p>
<p style="margin-bottom: 0.0001pt; line-height: 150%;"><b><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Finální podlahy:</span></b><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;"></span></p>
<p style="margin-bottom: 0.0001pt; line-height: 150%;"><i><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Koupelny (popřípadě koupelny s&nbsp;WC):</span></i><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">&nbsp;keramická dlažba a obklad do výšky stropů v&nbsp;ceně do 300,-/m2 včetně DPH bez liš a listel</span></p>
<p style="margin-bottom: 0.0001pt; line-height: 150%;"><i><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Samostatné WC, zádveří a technické místnosti:</span></i><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">&nbsp;keramická dlažba se soklem 8cm v&nbsp;ceně do 300,-/m2 včetně DPH bez liš a listel</span></p>
<p style="margin-bottom: 0.0001pt; line-height: 150%;"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Ostatní: linoleum popř. koberce v&nbsp;katalogové ceně do 300,-/m2 včetně DPH</span></p>
<p style="margin-bottom: 0.0001pt; line-height: 150%;"><b><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Venkovní terasy včetně jejich základů:&nbsp;</span></b><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Není součástí dodávky.</span></p>
<p style="margin-bottom: 0.0001pt; line-height: 150%;"><b><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Garážové stání :&nbsp;</span></b><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Není součástí dodávky</span></p>
<p style="margin-bottom: 0.0001pt; line-height: 150%;"><b><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Některé z&nbsp;možných víceprací:</span></b><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;"></span></p>
<p style="margin-bottom: 0.0001pt; line-height: 150%;"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">1.) - STROP pro pochozí skladovou půdu se zatížením 75kg/m2: Spodní kleštiny krovní KCE shora pobité OSB desky tl. 25mm popř. prkny tl. 25mm</span></p>
<p style="margin-bottom: 0.0001pt; line-height: 150%;"><span style="text-decoration: underline;"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Schody do půdního prostoru:</span></span><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;"></span></p>
<p style="margin-bottom: 0.0001pt; line-height: 150%;"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">sklápěcího schodiště TRIANT dřevo MINI</span></p>
<p style="margin-bottom: 0.0001pt; line-height: 150%;"><b><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">cena: 50.000,- bez DPH</span></b><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;"></span></p>
<p style="margin-bottom: 0.0001pt; line-height: 150%;"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">2.) Komín: s&nbsp;ohledem na výšku stavby není možno dodat, popřípadě speciální opatření</span></p>
<p style="margin-bottom: 0.0001pt; line-height: 150%;"><b><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">cena: xx.xxx,- bez DPH</span></b><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;"></span></p>
<p style="margin-bottom: 0.0001pt; line-height: 150%;"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">3.) Vnější fasáda v&nbsp;světlé barvě (bezpříplatkový odstín)</span></p>
<p style="margin-bottom: 0.0001pt; line-height: 150%;"><b><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">cena: 9.000,- bez DPH</span></b><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;"></span></p>
<p style="margin-bottom: 0.0001pt; line-height: 150%;"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Další možné vícepráce rádi doceníme dle vašich požadavků.&nbsp;</span></p> 
                </div>
<?php include("../includes/side-kontakt.php"); ?>
            </div>
<?php include("../includes/paticka.php"); ?>