<?php
    $title = "Bungalov 60 2+kk";
	$active = "typove-domy";
	include("../includes/hlavicka.php");
?>
            <div class="row-fluid">
                <div class="span8 well">
	<h2>KLASIK 218 7+kk</h2>

<p style="margin-bottom: 0cm;" class="western"><span style="font-family: arial, helvetica, sans-serif; font-size: 10pt;"><strong><img style="float: left; margin: 0px 20px 0px 0px;" alt="KLASIK 218" src="../images/typove_domy/KLASIK_218.jpg" width="204" height="114" /></strong></span></p>
<p style="margin-bottom: 0cm;" class="western"><span style="font-size: 10pt; font-family: tahoma, arial, helvetica, sans-serif;"><strong>Základní popis:</strong></span></p>
<p style="margin-top: 0.07cm; margin-bottom: 0.07cm;"><span style="font-size: 10pt; font-family: tahoma, arial, helvetica, sans-serif;"><strong>Počet podlaží:</strong> 2</span></p>
<p style="margin-top: 0.07cm; margin-bottom: 0.07cm;"><span style="font-size: 10pt; font-family: tahoma, arial, helvetica, sans-serif;"><strong>Dispozice:</strong> 7+kk</span></p>
<p style="margin-top: 0.07cm; margin-bottom: 0.07cm;"><span style="font-size: 10pt; font-family: tahoma, arial, helvetica, sans-serif;"><strong>Zastavěná plocha:</strong> 217,85m2</span></p>
<p style="margin-top: 0.07cm; margin-bottom: 0.07cm;"><span style="font-size: 10pt; font-family: tahoma, arial, helvetica, sans-serif;"><strong>Stavba na klíč:</strong> od 7.600.000,- bez DPH</span></p>
<p style="margin-top: 0.07cm; margin-bottom: 0.07cm;"><span style="font-size: 10pt; font-family: tahoma, arial, helvetica, sans-serif;"><strong>Hrubá stavba:</strong> od 4.300.000,- bez DPH</span></p>
<p style="margin-top: 0.07cm; margin-bottom: 0.07cm;"><span style="font-size: 10pt; font-family: tahoma, arial, helvetica, sans-serif;">Ceny uvedené pro základní vybavenost</span></p>
<p style="margin-bottom: 0cm;" class="western"><span style="font-family: arial, helvetica, sans-serif; font-size: 10pt;">&nbsp;</span></p>
<p style="margin-bottom: 0cm;" class="western"><span style="font-size: 10pt; font-family: tahoma, arial, helvetica, sans-serif;">Dům je velké rozměrové kategorie se sedmi obytnými místnostmi, jednou dvou garáží, jednou garáží pro zahradní techniku a sklepními vyhřívanými místnostmi s&nbsp;širokým využitím . Projekt možno vzrcadlit popřípadě jakkoliv upravit.</span></p>
<p style="margin-bottom: 0cm;" class="western"><span style="font-family: arial, helvetica, sans-serif; font-size: small;" size="2" face="arial, helvetica, sans-serif"><img alt="klasik 218s" src="../images/typove_domy_pudorysy/klasik_218s.jpg" width="266" height="250" /><img alt="klasik 218" src="../images/typove_domy_pudorysy/klasik_218.jpg" width="326" height="250" /><img alt="klasik 218p" src="../images/typove_domy_pudorysy/klasik_218p.jpg" width="260" height="250" /></span></p>
<p style="margin-bottom: 0cm;" class="western"><span style="font-family: arial, helvetica, sans-serif; font-size: small;" size="2" face="arial, helvetica, sans-serif"><b>&nbsp;</b></span></p>
<p style="margin-bottom: 0cm;" class="western"><span style="font-family: tahoma, arial, helvetica, sans-serif;"><b style="font-family: arial, helvetica, sans-serif; font-size: 10pt;">&nbsp;</b></span></p>
<p style="margin-bottom: 0cm;" class="western"><span style="font-family: tahoma, arial, helvetica, sans-serif;"><b style="font-family: arial, helvetica, sans-serif; font-size: 10pt;">Základní vybavenost:</b></span></p>
<p style="margin-bottom: 0cm;" class="western"><span style="font-size: 10pt; font-family: tahoma, arial, helvetica, sans-serif;" size="2" face="arial, helvetica, sans-serif"><b>Soupis dodaných prací včetně materiálů obsažených v ceně díla v základní vybavenosti<br />Varianta YTONG – HELUZ + dodatečné zateplení<br /></b></span></p>
<p style="margin-bottom: 0cm;" class="western"><span style="font-size: 10pt; font-family: tahoma, arial, helvetica, sans-serif;" size="2" face="arial, helvetica, sans-serif"><b>Příprava staveniště:</b></span></p>
<p style="margin-bottom: 0cm;" class="western"><span style="font-family: tahoma, arial, helvetica, sans-serif;"><span style="font-size: 10pt;" size="2" face="arial, helvetica, sans-serif"><b></b></span><span style="font-size: 10pt;">- příprava staveniště nutná pro realizaci</span></span></p>
<span style="font-size: 10pt; font-family: tahoma, arial, helvetica, sans-serif;">- zemní práce nutné před realizací stavby</span>
<div><span style="font-size: 10pt; font-family: tahoma, arial, helvetica, sans-serif;">- vytyčení stavby dle PD</span></div>
<div><span style="font-size: 10pt; font-family: tahoma, arial, helvetica, sans-serif;">- usazení na pozemek dle PD</span>
<p style="margin-bottom: 0cm;" class="western"><span style="font-family: tahoma, arial, helvetica, sans-serif;">&nbsp;</span></p>
<span style="font-family: tahoma, arial, helvetica, sans-serif;"><strong><span style="font-size: 10pt;">Základy a základová deska:</span></strong></span></div>
<div><span style="font-size: 10pt; font-family: tahoma, arial, helvetica, sans-serif;">- vyhloubení a vylití základových pásů včetně realizace potřebných průchodek dle PD</span><br /><span style="font-size: 10pt; font-family: tahoma, arial, helvetica, sans-serif;">- vyzdění a vybetonování ztraceného bednění nad úrovní základových pásů - výšky dle PD</span><br /><span style="font-size: 10pt; font-family: tahoma, arial, helvetica, sans-serif;">- vlastní betony základové desky včetně ležatých rozvodů kanalizace a vyústění průchodek</span><br /><span style="font-size: 10pt; font-family: tahoma, arial, helvetica, sans-serif;">- Hydro izolace lepenkou – max. STŘEDNÍ RADONOVÉ RIZIKO</span>
<p style="margin-bottom: 0cm;" class="western"><span style="font-family: tahoma, arial, helvetica, sans-serif;">&nbsp;</span></p>
<span style="font-family: tahoma, arial, helvetica, sans-serif;"><strong><span style="font-size: 10pt;">Svislé konstrukce:</span></strong><span style="font-size: 10pt;">- Vyzdění veškerého nosného zdiva</span></span><br /><span style="font-size: 10pt; font-family: tahoma, arial, helvetica, sans-serif;">Obvodové sklepní zdivo ZB popřípadě SILKA</span>
<p style="margin-bottom: 0cm;" class="western"><span style="font-family: tahoma, arial, helvetica, sans-serif;">&nbsp;</span></p>
<span style="font-family: tahoma, arial, helvetica, sans-serif;"><span style="font-size: 10pt;"><strong>Varianta HELUZ:</strong></span><span style="font-size: 10pt;">HELUZ PLUS 30 tl.300mm NA CELOPLOŠNÉ LEPILO včetně systémových . překladů + dodatečné zateplení viz úprava vnějších zdí</span></span><br /><span style="font-size: 10pt; font-family: tahoma, arial, helvetica, sans-serif;">Vyzdění vnitřních příček: HELUZ 11,5 na lepidlo včetně nenosných překladů</span>
<p style="margin-bottom: 0cm;" class="western"><span style="font-family: tahoma, arial, helvetica, sans-serif;">&nbsp;</span></p>
<span style="font-family: tahoma, arial, helvetica, sans-serif;"><strong><span style="font-size: 10pt;">Varianta YTONG:</span></strong></span><br /><span style="font-size: 10pt; font-family: tahoma, arial, helvetica, sans-serif;">YTONG P2-400 tl.300mm NA CELOPLOŠNÉ LEPILO včetně systémových . překladů + dodatečné zateplení viz úprava vnějších zdí</span><br /><span style="font-size: 10pt; font-family: tahoma, arial, helvetica, sans-serif;">Vyzdění vnitřních příček: YTONG tl.100 na lepidlo včetně nenosných překladů</span>
<p style="margin-bottom: 0cm;" class="western"><span style="font-family: tahoma, arial, helvetica, sans-serif;">&nbsp;</span></p>
<span style="font-size: 10pt; font-family: tahoma, arial, helvetica, sans-serif;">Vyhotovení železobetonového obvodového věnce nad nosným zdivem ve 2NP, sloužící taktéž pro ukotvení střešní KCE</span>
<p style="margin-bottom: 0cm;" class="western"><span style="font-family: tahoma, arial, helvetica, sans-serif;">&nbsp;</span></p>
<span style="font-family: tahoma, arial, helvetica, sans-serif;"><strong><span style="font-size: 10pt;">Vodorovné konstrukce:</span></strong><span style="font-size: 10pt;">Strop 1.PP a 1.NP: předpjaté dutinové panely dle PD včetně žel.bet. obvodového věnce</span></span><br /><span style="font-size: 10pt; font-family: tahoma, arial, helvetica, sans-serif;">Schodiště: 1. žel. bet. samonosné schodiště obložené dlažbou do 300,-m2 bez listel a lišt, 1 x samonosné celodřevěné otevřené schodiště se standardním celodřevěným zábradlím – materiál dub, buk s bezbarvým lakem</span>
<p style="margin-bottom: 0cm;" class="western"><span style="font-family: tahoma, arial, helvetica, sans-serif;">&nbsp;</span></p>
<span style="font-family: tahoma, arial, helvetica, sans-serif;"><strong><span style="font-size: 10pt;">Zastřešení stavby:</span></strong><span style="font-size: 10pt;">Krovy: příhradové vezníky s přesahy pobitými palubkami s bezbarvým lakem</span></span><br /><span style="font-size: 10pt; font-family: tahoma, arial, helvetica, sans-serif;">Tašky: KM-BETA klasik včetně všech potřebných doplňků – ČERVENÁ, ČERNÁ A HNĚDÁ BARVA BARVA</span><br /><span style="font-size: 10pt; font-family: tahoma, arial, helvetica, sans-serif;">Okapy, svody a oplechování: Pobarvený plech okapní svody budou zakončeny nad úrovní rostlého terénu</span><br /><span style="font-size: 10pt; font-family: tahoma, arial, helvetica, sans-serif;">Hromosvod: dle elektro projektu</span>
<p style="margin-bottom: 0cm;" class="western"><span style="font-family: tahoma, arial, helvetica, sans-serif;">&nbsp;</span></p>
<span style="font-family: tahoma, arial, helvetica, sans-serif;"><strong><span style="font-size: 10pt;">Zdravotechnika:</span></strong><span style="font-size: 10pt;">Voda:rozvody podlahách a zdech přivedené na místo připojení zařizovacích předmětů dle PD a zaslepeny. Hlavní přívod vody k vodoměrné šachtě do 10m.</span></span><br /><span style="font-size: 10pt; font-family: tahoma, arial, helvetica, sans-serif;">Výroba teplé užitkové vody zabezpečí bojler 160 l.</span><br /><span style="font-size: 10pt; font-family: tahoma, arial, helvetica, sans-serif;">Kanalizace:rozvody podlahách a zdech přivedené na místo připojení zařizovacích předmětů a zaslepeny. Hlavní přívod kanalizace k revizní kanalizační šachtě do 10m.</span>
<p style="margin-bottom: 0cm;" class="western"><span style="font-family: tahoma, arial, helvetica, sans-serif;">&nbsp;</span></p>
<span style="font-family: tahoma, arial, helvetica, sans-serif;"><strong><span style="font-size: 10pt;">Zařizovací předměty zdravotechniky:</span></strong><span style="font-size: 10pt;">2 x standardní WC kombi v ceně včetně ovládacího zařízení do 2.500,- /kus včetně DPH</span></span><br /><span style="font-size: 10pt; font-family: tahoma, arial, helvetica, sans-serif;">4 x umyvadlo včetně baterie v ceně do 2.500,- /kus včetně DPH</span><br /><span style="font-size: 10pt; font-family: tahoma, arial, helvetica, sans-serif;">2 x sprchový kout stavebnice s vlastní baterií v celkové ceně do 8.000,- /kus včetně DPH</span><br /><span style="font-size: 10pt; font-family: tahoma, arial, helvetica, sans-serif;">2 x vana včetně baterie v ceně do 6.500,- /kus včetně DPH</span>
<p style="margin-bottom: 0cm;" class="western"><span style="font-family: tahoma, arial, helvetica, sans-serif;">&nbsp;</span></p>
<span style="font-family: tahoma, arial, helvetica, sans-serif;"><strong><span style="font-size: 10pt;">Ústřední topení:</span></strong><span style="font-size: 10pt;">Zdrojem tepelné energie bude elektrokotel dle PD. Vlastní vytápění bude zabezpečeno celoplošným podlahovým vytápěním bez systémových desek – kotvení do podlahového polystyrénu na skoby. Mechanický pákový rozdělovač okruhů v systémové skříni.</span></span>
<p style="margin-bottom: 0cm;" class="western"><span style="font-family: tahoma, arial, helvetica, sans-serif;">&nbsp;</span></p>
<span style="font-family: tahoma, arial, helvetica, sans-serif;"><strong><span style="font-size: 10pt;">Elektroinstalace:</span></strong><span style="font-size: 10pt;">Veškeré rozvody kabeláže ve zdech a podlahách pro zásuvky, osvětlení, varnou desku, taktéž pro 1 x vnější zásuvku na 220V a 380V. V místě zásuvek a vypínačů krabice s kabeláží připravené pro jejich instalaci. V místě světel kabeláž ze stropu připravená pro napojení daného osvětlení. V místě připojení varné desky krabice s kabeláží pro připojení. V místě Bojleru krabice s kabeláží pro připojení. Vnitřní domovní rozvaděč s potřebnými jističi dle PD. Přivedení silového kabelu k vnějšímu rozvaděči RM do 10m. Osazení vypínačů a zásuvek modelu KLASIK výrobce ABB standard bílé barvy. Vlastní osvětlovací zařízení (lustry, svítidla, bodovky atd.) nejsou součástí dodávky. Počty zásuvek a světel jsou počítány dle PD v nižším standardu.</span></span>
<p style="margin-bottom: 0cm;" class="western"><span style="font-family: tahoma, arial, helvetica, sans-serif;">&nbsp;</span></p>
<span style="font-family: tahoma, arial, helvetica, sans-serif;"><strong><span style="font-size: 10pt;">Součástí dodávky nejsou nízkonapěťové, televizní a datové rozvody.</span></strong></span>
<p style="margin-bottom: 0cm;" class="western"><span style="font-family: tahoma, arial, helvetica, sans-serif;">&nbsp;</span></p>
<span style="font-size: 10pt; font-family: tahoma, arial, helvetica, sans-serif;">- kanalizační rozvody, rozvody TUV + SUV a elektro související s kuchyňskou linkou budou rozvedeny do předpokládaného místa připojení a zaslepeny.</span>
<p style="margin-bottom: 0cm;" class="western"><span style="font-family: tahoma, arial, helvetica, sans-serif;">&nbsp;</span></p>
<span style="font-family: tahoma, arial, helvetica, sans-serif;"><strong><span style="font-size: 10pt;">Výplně stavebních otvrů:</span></strong></span><br /><span style="font-size: 10pt; font-family: tahoma, arial, helvetica, sans-serif;"><strong>Vnějších</strong>:</span><br /><span style="font-size: 10pt; font-family: tahoma, arial, helvetica, sans-serif;">Okna, balkónové dveře:</span><br /><span style="font-size: 10pt; font-family: tahoma, arial, helvetica, sans-serif;">Dodavatel: VEKRA</span><br /><span style="font-size: 10pt; font-family: tahoma, arial, helvetica, sans-serif;">Provedení: plastové 5-ti komorová profil PRIMA</span><br /><span style="font-size: 10pt; font-family: tahoma, arial, helvetica, sans-serif;">Barevnost: vnější a vnitřní barva bílá stejná barevnost vnějších plechových a vnitřních plastových parapetů</span><br /><span style="font-size: 10pt; font-family: tahoma, arial, helvetica, sans-serif;">Zasklení: trojsklo bez okrasných vnitřních příček</span><br /><span style="font-size: 10pt; font-family: tahoma, arial, helvetica, sans-serif;">Vchodové dveře:</span><br /><span style="font-size: 10pt; font-family: tahoma, arial, helvetica, sans-serif;">Stejného systému jako okna s kováním vchodových dveří v patřičném profilu, výplň Izolační trojsklo popřípadě hladká deska</span><br /><span style="font-size: 10pt; font-family: tahoma, arial, helvetica, sans-serif;">Střešní okna: jsou li neprojektovány ROTO, VELUX základní</span><br /><span style="font-size: 10pt; font-family: tahoma, arial, helvetica, sans-serif;">Garážová vrata: pokud je součástí stavby garáž – rolovací s el. pohonem na dálkové ovládání bílé do 26.000,- bez DPH/kus/stavební otvor</span>
<p style="margin-bottom: 0cm;" class="western"><span style="font-family: tahoma, arial, helvetica, sans-serif;">&nbsp;</span></p>
<span style="font-size: 10pt; font-family: tahoma, arial, helvetica, sans-serif;">Vnitřních:</span><br /><span style="font-size: 10pt; font-family: tahoma, arial, helvetica, sans-serif;">Vnitřní dveře s obložkami:</span><br /><span style="font-size: 10pt; font-family: tahoma, arial, helvetica, sans-serif;">SAPELI STANDARD Model 10, 30, 40, 50, 60 a 65</span><br /><span style="font-size: 10pt; font-family: tahoma, arial, helvetica, sans-serif;">Vybavení: Standardní bezpříplatkové</span><br /><span style="font-size: 10pt; font-family: tahoma, arial, helvetica, sans-serif;">Sklo: dle výběru k danému tipu bezpříplatkové</span><br /><span style="font-size: 10pt; font-family: tahoma, arial, helvetica, sans-serif;">Povrch dveří i obložek: fólie - bílá, dub, buk, třešeň, javor, hruška, bělený dub, olše, teak, wenge</span><br /><span style="font-size: 10pt; font-family: tahoma, arial, helvetica, sans-serif;">Obložky: folie základního bezpříplatkového provedení potřebného tipu a materiálu ve vybrané barevnosti</span><br /><span style="font-size: 10pt; font-family: tahoma, arial, helvetica, sans-serif;">Zámkový set a kliku: Z důvodu velkého výběru dodá investor sám, popřípadě bude řešena dodávka jako vícepráce</span>
<p style="margin-bottom: 0cm;" class="western"><span style="font-family: tahoma, arial, helvetica, sans-serif;">&nbsp;</span></p>
<span style="font-size: 10pt; font-family: tahoma, arial, helvetica, sans-serif;">Finální úpravy povrchů zdí, stropů a schodiště:</span><br /><span style="font-size: 10pt; font-family: tahoma, arial, helvetica, sans-serif;">Vnější zdivo:</span><br /><span style="font-size: 10pt; font-family: tahoma, arial, helvetica, sans-serif;">- Pohledová boční strana základové desky obložená tepelnou izolací XPS tl.40mm ve viditelných částech natažená lepidlo + perlinka a okrasná zrnitá kamenitá fasáda</span><br /><span style="font-size: 10pt; font-family: tahoma, arial, helvetica, sans-serif;">- Vnější nosné zdivo: fasádní polystyrén EPS-F 70 tl.150mm + perlina + lepidlo + fasádní akrilátová omítka bílé barvy zrnitosti 1mm (točená)</span><br /><span style="font-size: 10pt; font-family: tahoma, arial, helvetica, sans-serif;">Vnitřní zdivo:</span><br /><span style="font-size: 10pt; font-family: tahoma, arial, helvetica, sans-serif;">VC malta + štuk popřípadě perlina+lepidlo+štuk</span><br /><span style="font-size: 10pt; font-family: tahoma, arial, helvetica, sans-serif;">Podhled stropů 1.NP:</span><br /><span style="font-size: 10pt; font-family: tahoma, arial, helvetica, sans-serif;">Sádrokartón začištěný + s tepelnou izolací vatou URSA tl.260mm</span><br /><span style="font-size: 10pt; font-family: tahoma, arial, helvetica, sans-serif;">Betonové mazaniny finálních podlah:</span><br /><span style="font-size: 10pt; font-family: tahoma, arial, helvetica, sans-serif;">- Podkladová tepelná izolace EPS-S dle PD a vlastní betony strojem hlazené</span><br /><span style="font-size: 10pt; font-family: tahoma, arial, helvetica, sans-serif;">Vnitřní vymalování:</span><br /><span style="font-size: 10pt; font-family: tahoma, arial, helvetica, sans-serif;">- Bílou barvou PRIMALEX</span>
<p style="margin-bottom: 0cm;" class="western"><span style="font-family: tahoma, arial, helvetica, sans-serif;">&nbsp;</span></p>
<span style="font-size: 10pt; font-family: tahoma, arial, helvetica, sans-serif;">Finální podlahy:</span><br /><span style="font-size: 10pt; font-family: tahoma, arial, helvetica, sans-serif;">Koupelny (popřípadě koupelny s WC): keramická dlažba a obklad do výšky stropů v ceně do 300,-/m2 včetně DPH bez liš a listel</span><br /><span style="font-size: 10pt; font-family: tahoma, arial, helvetica, sans-serif;">Samostatné WC, zádveří a technické místnosti: keramická dlažba se soklem 8cm v ceně do 300,-/m2 včetně DPH bez liš a listel</span><br /><span style="font-size: 10pt; font-family: tahoma, arial, helvetica, sans-serif;">Ostatní: linoleum popř. koberce v katalogové ceně do 300,-/m2 včetně DPH</span>
<p style="margin-bottom: 0cm;" class="western"><span style="font-family: tahoma, arial, helvetica, sans-serif;">&nbsp;</span></p>
<span style="font-size: 10pt; font-family: tahoma, arial, helvetica, sans-serif;">Venkovní terasy včetně jejich základů: Není součástí dodávky.</span>
<p style="margin-bottom: 0cm;" class="western"><span style="font-family: tahoma, arial, helvetica, sans-serif;">&nbsp;</span></p>
<span style="font-size: 10pt; font-family: tahoma, arial, helvetica, sans-serif;"><strong>Garážové stání :</strong> Není součástí dodávky</span>
<p style="margin-bottom: 0cm;" class="western"><span style="font-family: tahoma, arial, helvetica, sans-serif;">&nbsp;</span></p>
<span style="font-family: tahoma, arial, helvetica, sans-serif;"><strong><span style="font-size: 10pt;">Některé z možných víceprací:</span></strong></span>
<p style="margin-bottom: 0cm;" class="western"><span style="font-size: 10pt; font-family: tahoma, arial, helvetica, sans-serif;">2.) Komín HELUZ popř. SIKO s okrasnou imitací cihel nad úrovní střechy dle výběru dodavatel (bílá, červená), přívod vzduchu ve finálních podlahách k topnému mediu.</span></p>
<p style="margin-bottom: 0cm; margin-left: 30px;" class="western"><span style="font-size: 10pt; font-family: tahoma, arial, helvetica, sans-serif;">cena: 90.000,- bez DPH s jedním odkouřením pro KRB</span></p>
<p style="margin-bottom: 0cm;" class="western"><span style="font-size: 10pt; font-family: tahoma, arial, helvetica, sans-serif;">3.) Vnější fasáda v světlé barvě (bezpříplatkový odstín)</span></p>
<p style="margin-bottom: 0cm; margin-left: 30px;" class="western"><span style="font-size: 10pt; font-family: tahoma, arial, helvetica, sans-serif;">cena: 50.000,- bez DPH</span></p>
<span style="font-family: tahoma, arial, helvetica, sans-serif;"><span style="font-size: 10pt;">&nbsp;</span><span style="font-size: 10pt;">Další možné vícepráce rádi doceníme dle vašich požadavků.</span></span>
<p style="margin-bottom: 0cm;" class="western"><span style="font-size: 10pt; font-family: tahoma, arial, helvetica, sans-serif;" size="2" face="arial, helvetica, sans-serif"><b>&nbsp;</b></span></p>
</div>
                </div>
<?php include("../includes/side-kontakt.php"); ?>
            </div>
<?php include("../includes/paticka.php"); ?>