<?php
    $title = "KLASIK 125 4+kk";
	$active = "typove-domy";
	include("../includes/hlavicka.php");
?>
            <div class="row-fluid">
                <div class="span8 well">
	<h2>KLASIK 125 4+kk</h2>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><strong style="line-height: 150%;"><span size="2"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;"><img style="float: left; margin-right: 20px;" alt="KLASIK 125" src="../images/typove_domy/KLASIK_125.jpg" width="212" height="114" />Počet podlaží:</span></span></strong><span style="line-height: 150%;" size="2"><span class="apple-converted-space"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">&nbsp;</span></span><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">2</span></span></p>
<p style="margin: 0cm 0cm 2pt; line-height: 150%;"><span size="2"><b><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Dispozice:</span></b><span class="apple-converted-space"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">&nbsp;</span></span><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">4+kk</span></span></p>
<p style="margin: 0cm 0cm 2pt; line-height: 150%;"><strong><span size="2"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Zastavěná plocha:</span></span></strong><span size="2"><span class="apple-converted-space"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">&nbsp;</span></span><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">125m2</span></span></p>
<p style="margin: 0cm 0cm 2pt; line-height: 150%;"><strong><span size="2"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Stavba na klíč:</span></span></strong><span size="2"><span class="apple-converted-space"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">&nbsp;</span></span><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">od 3.410.000,- bez DPH</span></span></p>
<p style="margin: 0cm 0cm 2pt; line-height: 150%;"><strong><span size="2"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Hrubá stavba:</span></span></strong><span size="2"><span class="apple-converted-space"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">&nbsp;</span></span><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">od 1.870.000,- bez DPH</span></span></p>
<p style="margin: 0cm 0cm 2pt; line-height: 150%;"><span size="2"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Ceny uvedené pro základní vybavenost</span></span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">&nbsp;</span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><span size="2"><b><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;"><span class="apple-converted-space"></span></span></b><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Dům je střední rozměrové kategorie a je vhodný pro pěti až šesti člennou rodinu, za velmi příjemnou cenu. Projekt možno vzrcadlit popřípadě jakkoliv upravit.</span></span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">&nbsp;</span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;"><img alt="klasik 125" src="../images/typove_domy_pudorysy/klasik_125.jpg" width="406" height="260" /><img alt="klasik 125p" src="../images/typove_domy_pudorysy/klasik_125p.jpg" width="370" height="220" /></span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">&nbsp;</span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><span size="2"><b><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Základní vybavenost:</span></b></span><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;"></span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">&nbsp;</span></p>
<p style="margin: 0cm 0cm 0.0001pt; text-align: center; line-height: 150%;" class="western" align="center"><span size="2"><b><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Soupis dodaných prací včetně materiálů obsažených v&nbsp;ceně díla v&nbsp;základní vybavenosti</span></b></span><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;"></span></p>
<p style="margin: 0cm 0cm 0.0001pt; text-align: center; line-height: 150%;" class="western" align="center"><span size="2"><b><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Varianta YTONG – HELUZ + dodatečné zateplení</span></b></span><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;"></span></p>
<p style="margin: 0cm 0cm 0.0001pt; text-align: center; line-height: 150%;" class="western" align="center"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">&nbsp;</span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">&nbsp;</span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><span size="2"><b><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Příprava staveniště:</span></b></span><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;"></span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><span size="2"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">- příprava staveniště nutná pro realizaci</span></span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><span size="2"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">- zemní práce nutné před realizací stavby</span></span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><span size="2"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">- vytyčení stavby dle PD</span></span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><span size="2"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">- usazení na pozemek dle PD</span></span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">&nbsp;</span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><span size="2"><b><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Základy a základová deska:</span></b></span><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;"></span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><span size="2"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">- vyhloubení a vylití základových pásů včetně realizace potřebných průchodek dle PD</span></span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><span size="2"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">- vyzdění a vybetonování ztraceného bednění nad úrovní základových pásů - výšky dle PD</span></span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><span size="2"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">- vlastní betony základové desky včetně ležatých rozvodů kanalizace a vyústění průchodek</span></span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><span size="2"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">- Hydro izolace lepenkou – max. STŘEDNÍ RADONOVÉ RIZIKO</span></span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">&nbsp;</span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><span size="2"><b><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Svislé konstrukce:</span></b></span><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;"></span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><span size="2"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">- Vyzdění veškerého nosného zdiva</span></span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><span size="2"><i><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Varianta HELUZ:</span></i></span><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;"></span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><span size="2"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">HELUZ PLUS 30 tl.300mm NA CELOPLOŠNÉ LEPILO včetně systémových . překladů + dodatečné zateplení viz úprava vnějších zdí</span></span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><span size="2"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Vyzdění vnitřních příček: HELUZ 11,5 na lepidlo včetně nenosných překladů</span></span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">&nbsp;</span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><span size="2"><i><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Varianta YTONG:</span></i></span><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;"></span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><span size="2"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">YTONG P2-400 tl.300mm NA CELOPLOŠNÉ LEPILO včetně systémových . překladů + dodatečné zateplení viz úprava vnějších zdí</span></span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><span size="2"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Vyzdění vnitřních příček: YTONG tl.100 na lepidlo včetně nenosných překladů</span></span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">&nbsp;</span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><span size="2"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Vyhotovení železobetonového obvodového věnce nad nosným zdivem ve 2NP, sloužící taktéž pro ukotvení střešní KCE</span></span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">&nbsp;</span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><span size="2"><b><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Vodorovné konstrukce:</span></b></span><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;"></span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><span size="2"><span><span style="text-decoration: underline;"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Strop 1.NP:</span></span></span><span class="apple-converted-space"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">&nbsp;</span></span><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">předpjaté dutinové panely dle PD včetně žel.bet. obvodového věnce</span></span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><span size="2"><span><span style="text-decoration: underline;"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Schodiště:</span></span></span><span class="apple-converted-space"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">&nbsp;</span></span><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">samonosné dřevěné schodiště se standardním dřevěným zábradlím – dub, buk bezbarvý lak</span></span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">&nbsp;</span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><span size="2"><b><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Zastřešení stavby:</span></b></span><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;"></span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><span size="2"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Krovy: klasické krovy s&nbsp;hoblovanými přesahy pobitými palubkami shora natřenými bezbarvým lakem</span></span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><span size="2"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Tašky: KM-BETA klasik včetně všech potřebných doplňků – ČERVENÁ, ČERNÁ A HNĚDÁ BARVA BARVA</span></span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><span size="2"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Okapy, svody a oplechování: Pobarvený plech okapní svody budou zakončeny nad úrovní rostlého terénu</span></span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><span size="2"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Hromosvod: dle elektro projektu</span></span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">&nbsp;</span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><span size="2"><b><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Zdravotechnika:</span></b></span><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;"></span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><span size="2"><span><span style="text-decoration: underline;"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Voda:</span></span></span><span class="apple-converted-space"><b><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">&nbsp;</span></b></span><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">rozvody podlahách a zdech přivedené na místo připojení zařizovacích předmětů dle PD a zaslepeny. Hlavní přívod vody k&nbsp;vodoměrné šachtě do 10m.</span></span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><span size="2"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Výroba teplé užitkové vody zabezpečí bojler 160 l.</span></span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><span size="2"><span><span style="text-decoration: underline;"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Kanalizace:</span></span></span><span class="apple-converted-space"><b><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">&nbsp;</span></b></span><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">rozvody podlahách a zdech přivedené na místo připojení zařizovacích předmětů a zaslepeny. Hlavní přívod kanalizace k&nbsp;revizní kanalizační šachtě do 10m.</span></span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">&nbsp;</span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><span size="2"><span><span style="text-decoration: underline;"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Zařizovací předměty zdravotechniky:</span></span></span></span><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;"></span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><span size="2"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">3 x standardní WC kombi v&nbsp;ceně včetně ovládacího zařízení do 2.500,- /kus včetně DPH</span></span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><span size="2"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">3 x umyvadlo včetně baterie v&nbsp;ceně do 2.500,- /kus včetně DPH</span></span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><span size="2"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">2 x sprchový kout stavebnice s&nbsp;vlastní baterií v&nbsp;celkové ceně do 8.000,- /kus včetně DPH</span></span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><span size="2"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">1 x vana včetně baterie v&nbsp;ceně do 6.500,- /kus včetně DPH</span></span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">&nbsp;</span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><span size="2"><b><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Ústřední topení:</span></b></span><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;"></span></p>
<p style="margin-top: 0cm; line-height: 150%;" class="western"><span size="2"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Zdrojem tepelné energie bude elektrokotel dle PD. Vlastní vytápění bude zabezpečeno celoplošným podlahovým vytápěním bez systémových desek – kotvení do podlahového polystyrénu na skoby. Mechanický pákový rozdělovač okruhů v&nbsp;systémové skříni.</span></span></p>
<p style="margin-top: 0cm; line-height: 150%;" class="western"><span size="2"><b><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Elektroinstalace:</span></b></span><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;"></span></p>
<p style="margin-top: 0cm; line-height: 150%;" class="western"><span size="2"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Veškeré rozvody kabeláže ve zdech a podlahách pro zásuvky, osvětlení, varnou desku, taktéž pro 1 x vnější zásuvku na 220V a 380V. V&nbsp;místě zásuvek a vypínačů krabice s&nbsp;kabeláží připravené pro jejich instalaci. V&nbsp;místě světel kabeláž ze stropu připravená pro napojení daného osvětlení. V&nbsp;místě připojení varné desky krabice s&nbsp;kabeláží pro připojení. V&nbsp;místě Bojleru krabice s kabeláží pro připojení. Vnitřní domovní rozvaděč s&nbsp;potřebnými jističi dle PD. Přivedení silového kabelu k&nbsp;vnějšímu rozvaděči RM do 10m. Osazení vypínačů a zásuvek modelu KLASIK výrobce ABB standard bílé barvy. Vlastní osvětlovací zařízení (lustry, svítidla, bodovky atd.) nejsou součástí dodávky. Počty zásuvek a světel jsou počítány dle PD v&nbsp;nižším standardu.</span></span></p>
<p style="margin-top: 0cm; line-height: 150%;" class="western"><span size="2"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Součástí dodávky nejsou nízkonapěťové, televizní a datové rozvody.</span></span></p>
<p style="margin-top: 0cm; line-height: 150%;" class="western"><span size="2"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">- kanalizační rozvody, rozvody TUV + SUV a elektro související s&nbsp;kuchyňskou linkou budou rozvedeny do předpokládaného místa připojení a zaslepeny.</span></span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">&nbsp;</span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><span size="2"><b><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Výplně stavebních otvrů:</span></b></span><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;"></span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><span size="2"><b><i><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Vnějších:</span></i></b></span><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;"></span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><span size="2"><span><span style="text-decoration: underline;"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Okna, balkónové dveře:</span></span></span></span><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;"></span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><span size="2"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Dodavatel:<span class="apple-converted-space">&nbsp;</span><b>VEKRA</b></span></span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><span size="2"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Provedení: plastové 5-ti komorová profil<span class="apple-converted-space">&nbsp;</span><b>PRIMA</b></span></span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><span size="2"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Barevnost: vnější a vnitřní barva bílá stejná barevnost vnějších plechových a vnitřních plastových parapetů</span></span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><span size="2"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Zasklení: trojsklo bez okrasných vnitřních příček</span></span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><span size="2"><span><span style="text-decoration: underline;"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Vchodové dveře:</span></span></span></span><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;"></span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><span size="2"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Stejného systému jako okna s&nbsp;kováním vchodových dveří v&nbsp;patřičném profilu, výplň Izolační trojsklo popřípadě hladká deska</span></span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><span size="2"><span><span style="text-decoration: underline;"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Střešní okna:</span></span></span><span class="apple-converted-space"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">&nbsp;</span></span><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">jsou li neprojektovány ROTO, VELUX základní</span></span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><span size="2"><span><span style="text-decoration: underline;"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Garážová vrata:</span></span></span><span class="apple-converted-space"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">&nbsp;</span></span><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">pokud je součástí stavby garáž – rolovací s&nbsp;el. pohonem na dálkové ovládání bílé do 26.000,- bez DPH/kus/stavební otvor</span></span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">&nbsp;</span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><span size="2"><b><i><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Vnitřních:</span></i></b></span><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;"></span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><span size="2"><span><span style="text-decoration: underline;"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Vnitřní dveře s&nbsp;obložkami:</span></span></span></span><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;"></span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><span size="2"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">SAPELI STANDARD Model 10, 30, 40, 50, 60 a 65</span></span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><span size="2"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Vybavení: Standardní bezpříplatkové</span></span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><span size="2"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Sklo: dle výběru k&nbsp;danému tipu bezpříplatkové</span></span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><span size="2"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Povrch dveří i obložek: fólie - bílá, dub, buk, třešeň, javor, hruška, bělený dub, olše, teak, wenge</span></span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><span size="2"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Obložky: folie základního bezpříplatkového provedení potřebného tipu a materiálu ve vybrané barevnosti</span></span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><span size="2"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Zámkový set a kliku: Z&nbsp;důvodu velkého výběru dodá investor sám, popřípadě bude řešena dodávka jako vícepráce</span></span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">&nbsp;</span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><span size="2"><b><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Finální úpravy povrchů zdí, stropů a schodiště:</span></b></span><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;"></span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><span size="2"><span><span style="text-decoration: underline;"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Vnější zdivo:</span></span></span></span><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;"></span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><span size="2"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">- Pohledová boční strana základové desky obložená tepelnou izolací XPS tl.40mm ve viditelných částech natažená lepidlo + perlinka a okrasná zrnitá kamenitá fasáda</span></span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><span size="2"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">- Vnější nosné zdivo: fasádní polystyrén EPS-F 70 tl.150mm + perlina + lepidlo + fasádní akrilátová omítka bílé barvy zrnitosti 1mm (točená)</span></span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><span size="2"><span><span style="text-decoration: underline;"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Vnitřní zdivo:</span></span></span></span><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;"></span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><span size="2"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">VC malta + štuk popřípadě perlina+lepidlo+štuk</span></span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><span size="2"><span><span style="text-decoration: underline;"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Podhled stropů 1.NP:</span></span></span></span><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;"></span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><span size="2"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Sádrokartón začištěný + s&nbsp;tepelnou izolací vatou URSA tl.260mm</span></span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><span size="2"><span><span style="text-decoration: underline;"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Betonové mazaniny finálních podlah:</span></span></span></span><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;"></span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><span size="2"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">- Podkladová tepelná izolace EPS-S dle PD a vlastní betony strojem hlazené</span></span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><span size="2"><span><span style="text-decoration: underline;"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Vnitřní vymalování:</span></span></span></span><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;"></span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><span size="2"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">- Bílou barvou PRIMALEX</span></span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">&nbsp;</span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><span size="2"><b><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Finální podlahy:</span></b></span><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;"></span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><span size="2"><i><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Koupelny (popřípadě koupelny s&nbsp;WC):</span></i><span class="apple-converted-space"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">&nbsp;</span></span><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">keramická dlažba a obklad do výšky stropů v&nbsp;ceně do 300,-/m2 včetně DPH bez liš a listel</span></span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><span size="2"><i><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Samostatné WC, zádveří a technické místnosti:</span></i><span class="apple-converted-space"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">&nbsp;</span></span><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">keramická dlažba se soklem 8cm v&nbsp;ceně do 300,-/m2 včetně DPH bez liš a listel</span></span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><span size="2"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Ostatní: linoleum popř. koberce v&nbsp;katalogové ceně do 300,-/m2 včetně DPH</span></span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">&nbsp;</span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><span size="2"><b><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Venkovní terasy včetně jejich základů:<span class="apple-converted-space">&nbsp;</span></span></b><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Není součástí dodávky.</span></span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">&nbsp;</span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><span size="2"><b><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Garážové stání :<span class="apple-converted-space">&nbsp;</span></span></b><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Není součástí dodávky</span></span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">&nbsp;</span></p>
<p style="margin: 0cm 0cm 0.0001pt; text-align: center; line-height: 150%;" class="western" align="center"><span size="4"><b><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Některé z&nbsp;možných víceprací:</span></b></span><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;"></span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">&nbsp;</span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><span size="2"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">2.) Komín HELUZ popř. SIKO s&nbsp;okrasnou imitací cihel nad úrovní střechy dle výběru dodavatel (bílá, červená), přívod vzduchu ve finálních podlahách k&nbsp;topnému mediu.</span></span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">&nbsp;</span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><span size="2"><b><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">cena: 50.000,- bez DPH/kus</span></b></span><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;"></span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">&nbsp;</span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><span size="2"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">3.) Vnější fasáda v&nbsp;světlé barvě (bezpříplatkový odstín)</span></span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">&nbsp;</span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><span size="2"><b><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">cena: 40.000,- bez DPH</span></b></span><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;"></span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 150%;" class="western"><span size="2"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">Další možné vícepráce rádi doceníme dle vašich požadavků.</span></span></p>
<p style="line-height: 150%;"><span style="font-size: 10pt; line-height: 150%; font-family: Tahoma, sans-serif;">&nbsp;</span></p> 
                </div>
<?php include("../includes/side-kontakt.php"); ?>
            </div>
<?php include("../includes/paticka.php"); ?>